### 1. 휴대폰 인증 번호 전송
POST {{url}}/v1/accounts/send-auth-code
Content-Type: application/json

{
  "phoneNumber": "{{phoneNumber}}"
}

### 2. 휴대폰 인증 번호 검증
POST {{url}}/v1/accounts/verify-auth-code
Content-Type: application/json

{
  "phoneNumber": "{{phoneNumber}}",
  "code": 849031
}

### 3. 회원 가입
POST {{url}}/v1/accounts
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "phoneNumber": "{{phoneNumber}}"
}

### 4. 이메일 인증 확인 메일 전송
POST {{url}}/v1/accounts/send-auth-mail
Content-Type: application/json

{
  "email": "{{email}}"
}

### 5. 이메일 인증 확인 메일 검증
POST {{url}}/v1/accounts/verify-auth-mail?
    token=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIxIiwic3ViIjoiaGFuZHdvb25nQGdtYWlsLmNvbSIsImlhdCI6MTc0NjM0NTk0NCwiZXhwIjoxNzQ2NDMyMzQ0fQ.RKgCzXchK4xuQ1_OK-onYmRKL2fVMScyYdKQciy48UOQQhoJWAoK6uYpwh_x1MM9XGwkOT72GrrSLjankI0Exg
Content-Type: application/json

### 6. 로그인
POST {{url}}/v1/accounts/sign-in
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

### 6. 관리자 로그인
POST {{url}}/v1/accounts/sign-in
Content-Type: application/json

{
  "email": "{{admin}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

### 7. 토큰 갱신
POST {{url}}/v1/accounts/renew-token
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

### 8. 프로필 조회
GET {{url}}/v1/accounts/me
Authorization: Bearer {{accessToken}}
