### 1. 매장 목록 조회
GET {{url}}/v1/stores
Authorization: Bearer {{accessToken}}

### 2. 매장 상세 조회
GET {{url}}/v1/stores/706810975107825958

### 3. 매장 정보 수정
PUT {{url}}/v1/stores/706810975107825958
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "landline": "055-123-4567",
  "setting": {
    "ksnetDeviceNo": "DPTOTEST01",
    "extraTableCount": 5,
    "printerLocation": "POS",
    "showMenuPopup": true,
    "showOrderTotalPrice": true,
    "countryOfOrigins": [
      {
        "item": "돼지고기",
        "origin": "국내산"
      },
      {
        "item": "소고기",
        "origin": "국내산"
      }
    ],
    "staffCallOptions": [
      "직원 호출",
      "포장"
    ]
  }
}
