### 1. 매장 오픈
< {%
  const deviceId = request.environment.get("devices.pos.id");
  const deviceName = request.environment.get("devices.pos.name");
  const devicePurpose = request.environment.get("devices.pos.purpose");
  const secretKey = request.environment.get("devices.pos.secretKey");

  const method = request.method;
  const uri = request.url
  .tryGetSubstituted()
  .split(request.environment.get("url"))[1];
  const timestamp = Date.now().toString();

  const signature = crypto.hmac.sha256()
  .withTextSecret(secretKey)
  .updateWithText(`${method} ${uri}\n`)
  .updateWithText(`${deviceId} ${devicePurpose} ${deviceName}\n`)
  .updateWithText(`${timestamp}`)
  .digest()
  .toBase64();

  request.variables.set("accessKey", deviceId);
  request.variables.set("signature", signature);
  request.variables.set("timestamp", timestamp);
%}

POST {{url}}/v1/stores/open
Content-Type: application/json
x-ew-access-key: {{accessKey}}
x-ew-signature: {{signature}}
x-ew-timestamp: {{timestamp}}

### 2. 매장 마감
< {%
  const deviceId = request.environment.get("devices.pos.id");
  const deviceName = request.environment.get("devices.pos.name");
  const devicePurpose = request.environment.get("devices.pos.purpose");
  const secretKey = request.environment.get("devices.pos.secretKey");

  const method = request.method;
  const uri = request.url
  .tryGetSubstituted()
  .split(request.environment.get("url"))[1];
  const timestamp = Date.now().toString();

  const signature = crypto.hmac.sha256()
  .withTextSecret(secretKey)
  .updateWithText(`${method} ${uri}\n`)
  .updateWithText(`${deviceId} ${devicePurpose} ${deviceName}\n`)
  .updateWithText(`${timestamp}`)
  .digest()
  .toBase64();

  request.variables.set("accessKey", deviceId);
  request.variables.set("signature", signature);
  request.variables.set("timestamp", timestamp);
%}

POST {{url}}/v1/stores/close
Content-Type: application/json
x-ew-access-key: {{accessKey}}
x-ew-signature: {{signature}}
x-ew-timestamp: {{timestamp}}
