### 1. 웨이팅 등록
< {%
  const deviceId = request.environment.get("devices.waiting.id");
  const deviceName = request.environment.get("devices.waiting.name");
  const devicePurpose = request.environment.get("devices.waiting.purpose");
  const secretKey = request.environment.get("devices.waiting.secretKey");

  const method = request.method;
  const uri = request.url
  .tryGetSubstituted()
  .split(request.environment.get("url"))[1];
  const timestamp = Date.now().toString();

  const signature = crypto.hmac.sha256()
  .withTextSecret(secretKey)
  .updateWithText(`${method} ${uri}\n`)
  .updateWithText(`${deviceId} ${devicePurpose} ${deviceName}\n`)
  .updateWithText(`${timestamp}`)
  .digest()
  .toBase64();

  request.variables.set("accessKey", deviceId);
  request.variables.set("signature", signature);
  request.variables.set("timestamp", timestamp);
%}

POST {{url}}/v1/waitings
Content-Type: application/json
x-ew-access-key: {{accessKey}}
x-ew-signature: {{signature}}
x-ew-timestamp: {{timestamp}}

{
  "phoneNumber": "01044591812",
  "adult": 2,
  "infant": 0
}
